[profile.default]
src = 'contracts'
test = 'test/foundry'
libs = ['lib','node_modules']
remappings = ['forge-std/=lib/forge-std/src/','ds-test/=lib/forge-std/lib/ds-test/src/']
optimizer = true
optimizer_runs = 1337

# See more config options https://github.com/foundry-rs/foundry/tree/master/config